### ISSUE TITLE
Scope / naming: bvgmatch-server

### ISSUE THREAD

**Issue by MarkusTiede** [stiftung-auffangeinrichtung-bvg/bvgmatch-server#5]
The name of the project might suggest that it will also contain server components in the upcoming future; I guess it's only supposed to contain the API specification for the service or do you also plan adding runtime components to this repository.

If not it might be more useful having a name like "bvgmatch-api" or similar to reflect the scope.

**Comment by marcospescha** [comment]
It is not decided yet, if we will add server components or just the API spec. We leave the name as is until the next phase of the project when we decided which components will be open source.
